version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/order_app?allowPublicKeyRetrieval=true&useSSL=false
      - SPRING_DATASOURCE_USERNAME=nikos
      - SPRING_DATASOURCE_PASSWORD=nikos
    depends_on:
      - db
    networks:
      - spring-mysql-network

  db:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=order_app
      - MYSQL_USER=nikos
      - MYSQL_PASSWORD=nikos
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql-network

volumes:
  mysql-data:

networks:
  spring-mysql-network:
    driver: bridge